server:
  port: 8085

spring:
  jpa:
    hibernate:
      ddl-auto : update
    show-sql : true
    generate-ddl: true

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
  profiles:
    active: local
  application:
    name: THB-DESABASE-SYSTEM
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/thb
    username: postgres
    password: faqihbuana2022

  mail:
    host: smtp.gmail.com
    port: 587
    username: iamfaqih.rochman@gmail.com
    password: pwiu ccxh hsfe kkcn
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: http://localhost:8084


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token: 604800000 # 7 days

#LOGGING
logging:
  level:
    com:
      thbdesabase:
        orderServices: debug
    org:
      hibernate:
        SQL : debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
